-- 4. TAO TABLE [#tblResult] tu table [#tblResource]
USE NTT_PRAC
GO

DROP TABLE IF EXISTS #tblResource
CREATE TABLE #tblResource
(
    Id int IDENTITY,
    Code NVARCHAR(24),
    Value INT
)

INSERT INTO #tblResource(Code,[Value])
SELECT 'A',100
UNION ALL
SELECT 'B',200
UNION ALL
SELECT 'C',150
UNION ALL
SELECT 'A',300
UNION ALL
SELECT 'B',240
UNION ALL
SELECT 'A',120
UNION ALL
SELECT 'C',130

SELECT Id,ROW_NUMBER() OVER (PARTITION BY CODE ORDER BY CODE ASC) AS ORDER_ROW,CODE,[Value]  FROM #tblResource
ORDER BY Code,VALUE